import Foundation
import AppKit

// MARK: - Screenshot and prompt helpers

/// Returns the prompt with all "[Screenshot attached: path]" references removed, trimmed. Use for display only.
func userPromptDisplayText(from prompt: String) -> String {
    let pattern = "\\s*\\[Screenshot attached:\\s*[^\\]]+\\]\\s*"
    guard let regex = try? NSRegularExpression(pattern: pattern) else { return prompt }
    let range = NSRange(prompt.startIndex..., in: prompt)
    let stripped = regex.stringByReplacingMatches(
        in: prompt,
        range: range,
        withTemplate: "\n"
    )
    return stripped
        .components(separatedBy: .newlines)
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .joined(separator: "\n")
        .trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Extracts screenshot paths from prompt (e.g. ".cursor/pasted-screenshot-1.png"), capped at maxScreenshots.
func screenshotPaths(from prompt: String) -> [String] {
    let pattern = "\\[Screenshot attached:\\s*([^\\]]+)\\]"
    guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
    let range = NSRange(prompt.startIndex..., in: prompt)
    let matches = regex.matches(in: prompt, range: range)
    var paths: [String] = []
    for m in matches {
        if m.numberOfRanges > 1, let r = Range(m.range(at: 1), in: prompt) {
            let path = String(prompt[r]).trimmingCharacters(in: .whitespaces)
            if !path.isEmpty, !paths.contains(path) {
                paths.append(path)
            }
        }
    }
    return Array(paths.prefix(AppLimits.maxScreenshots))
}

func estimatedContextTokens(prompt: String, conversationCharacterCount: Int) -> (used: Int, limit: Int) {
    let chars = prompt.count + conversationCharacterCount
    let used = max(0, chars / 4)
    return (used, AppLimits.contextTokenLimit)
}

func autoGeneratedTabTitle(from prompt: String) -> String? {
    let firstContentLine = prompt
        .components(separatedBy: .newlines)
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .first { !$0.isEmpty && !$0.hasPrefix("[Screenshot attached:") }

    if let firstContentLine {
        let normalized = firstContentLine.replacingOccurrences(
            of: #"\s+"#,
            with: " ",
            options: .regularExpression
        )
        let truncated = String(normalized.prefix(72)).trimmingCharacters(in: .whitespacesAndNewlines)
        if !truncated.isEmpty { return truncated }
    }

    // Prompt is empty or only screenshot(s) — use a fallback so the tab doesn't stay "Agent N"
    if !screenshotPaths(from: prompt).isEmpty {
        return "Screenshot"
    }

    return nil
}

/// Picks the next available screenshot filename not in current paths (legacy workspace-relative paths).
func nextScreenshotPath(currentPaths: [String]) -> String? {
    let legacy = ".cursor/pasted-screenshot.png"
    if !currentPaths.contains(legacy) { return legacy }
    for i in 1...AppLimits.maxScreenshots {
        let candidate = ".cursor/pasted-screenshot-\(i).png"
        if !currentPaths.contains(candidate) { return candidate }
    }
    return nil
}

// MARK: - Screenshot cache (tmp in app support, same location as preferences/tab state)

/// Directory where pasted screenshots are stored: ~/Library/Application Support/CursorPlus/tmp. Creates the directory if needed.
func screenshotCacheDirectoryURL() -> URL {
    let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
    let dir = base.appendingPathComponent("CursorPlus", isDirectory: true).appendingPathComponent("tmp", isDirectory: true)
    try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
    return dir
}

/// Returns a unique full path for a new screenshot in the cache (for use in [Screenshot attached: path]).
func nextScreenshotCachePath() -> String {
    screenshotCacheDirectoryURL()
        .appendingPathComponent("\(UUID().uuidString).png")
        .path
}

/// Resolves a screenshot path from a prompt to a file URL. Path may be absolute (cache) or workspace-relative (legacy).
/// Use this when loading or deleting; missing files are handled by callers (e.g. NSImage(contentsOf:) returns nil).
func screenshotFileURL(path: String, workspacePath: String) -> URL {
    let trimmed = path.trimmingCharacters(in: .whitespaces)
    if trimmed.hasPrefix("/") {
        return URL(fileURLWithPath: trimmed)
    }
    return URL(fileURLWithPath: workspacePath).appendingPathComponent(trimmed)
}

/// Deletes screenshot cache files older than the given number of days. Call on app quit.
func deleteScreenshotCacheOlderThan(days: Int) {
    let dir = screenshotCacheDirectoryURL()
    let cutoff = Date().addingTimeInterval(-Double(days * 24 * 60 * 60))
    guard let contents = try? FileManager.default.contentsOfDirectory(
        at: dir,
        includingPropertiesForKeys: [.contentModificationDateKey],
        options: [.skipsHiddenFiles]
    ) else { return }
    for url in contents where url.pathExtension.lowercased() == "png" {
        guard let date = (try? url.resourceValues(forKeys: [.contentModificationDateKey]))?.contentModificationDate else { continue }
        if date < cutoff {
            try? FileManager.default.removeItem(at: url)
        }
    }
}

// MARK: - Project root (terminal / process working directory)

/// Returns the project root for running terminal or process. If `workspacePath` ends with `/.metro`, returns the parent directory so the shell/agent runs in the project root, not inside `.metro`.
func projectRootForTerminal(workspacePath: String) -> String {
    let trimmed = workspacePath.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return trimmed }
    let expanded = (trimmed as NSString).expandingTildeInPath
    let url = URL(fileURLWithPath: expanded)
    if url.lastPathComponent == ".metro" {
        return url.deletingLastPathComponent().path
    }
    return expanded
}

// MARK: - Project folders and Git

/// Returns immediate subdirectories of `rootPath` that contain a `.metro` directory (Metro projects only).
func loadDevFolders(rootPath: String) -> [URL] {
    let resolvedRootPath = AppPreferences.resolvedProjectsRootPath(rootPath)
    let url = URL(fileURLWithPath: resolvedRootPath)
    guard let contents = try? FileManager.default.contentsOfDirectory(
        at: url,
        includingPropertiesForKeys: [.isDirectoryKey],
        options: [.skipsHiddenFiles]
    ) else { return [] }
    let fm = FileManager.default
    return contents
        .filter { candidate in
            guard (try? candidate.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return false }
            let metroDir = candidate.appendingPathComponent(".metro", isDirectory: true)
            var isDir: ObjCBool = false
            return fm.fileExists(atPath: metroDir.path, isDirectory: &isDir) && isDir.boolValue
        }
        .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }
}

/// Reads the default branch name from .git/HEAD (e.g. "ref: refs/heads/main" -> "main"). Returns nil if not a symbolic ref or not a git repo.
func gitDefaultBranchName(workspacePath: String) -> String? {
    let headURL = URL(fileURLWithPath: workspacePath).appendingPathComponent(".git/HEAD", isDirectory: false)
    guard let content = try? String(contentsOf: headURL, encoding: .utf8) else { return nil }
    let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
    let prefix = "ref: refs/heads/"
    guard trimmed.hasPrefix(prefix) else { return nil }
    let name = String(trimmed.dropFirst(prefix.count)).trimmingCharacters(in: .whitespacesAndNewlines)
    return name.isEmpty ? nil : name
}

/// Returns (current branch name, sorted list of local branch names) for the workspace. Empty if not a git repo.
func loadGitBranches(workspacePath: String) -> (current: String, branches: [String]) {
    let url = URL(fileURLWithPath: workspacePath)
    guard (try? url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return ("", []) }
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["for-each-ref", "--format=%(refname:short)", "refs/heads/"]
    process.currentDirectoryURL = url
    let pipe = Pipe()
    process.standardOutput = pipe
    process.standardError = FileHandle.nullDevice
    guard (try? process.run()) != nil else { return ("", []) }
    process.waitUntilExit()
    guard process.terminationStatus == 0 else { return ("", []) }
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    var list = (String(data: data, encoding: .utf8) ?? "")
        .split(separator: "\n")
        .map(String.init)
        .filter { !$0.isEmpty }
        .sorted { $0.localizedStandardCompare($1) == .orderedAscending }
    let currentProcess = Process()
    currentProcess.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    currentProcess.arguments = ["rev-parse", "--abbrev-ref", "HEAD"]
    currentProcess.currentDirectoryURL = url
    let currentPipe = Pipe()
    currentProcess.standardOutput = currentPipe
    currentProcess.standardError = FileHandle.nullDevice
    guard (try? currentProcess.run()) != nil else { return (list.first ?? "", list) }
    currentProcess.waitUntilExit()
    let currentData = currentPipe.fileHandleForReading.readDataToEndOfFile()
    var current = (String(data: currentData, encoding: .utf8) ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
    // Fresh git init: no commits yet so rev-parse returns "HEAD" but .git/HEAD points to refs/heads/main (or init.defaultBranch). Show that name.
    if current == "HEAD", list.isEmpty, let defaultBranch = gitDefaultBranchName(workspacePath: workspacePath) {
        current = defaultBranch
        list = [defaultBranch]
    }
    return (current.isEmpty ? (list.first ?? "") : current, list)
}

/// Run `git checkout <branch>` in the workspace. Returns nil on success, error message otherwise.
func gitCheckout(branch: String, workspacePath: String) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["checkout", branch]
    process.currentDirectoryURL = URL(fileURLWithPath: workspacePath)
    let pipe = Pipe()
    process.standardOutput = pipe
    let errPipe = Pipe()
    process.standardError = errPipe
    guard (try? process.run()) != nil else { return "Failed to run git" }
    process.waitUntilExit()
    guard process.terminationStatus != 0 else { return nil }
    let err = (try? String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)) ?? "Unknown error"
    return err.trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Create a new branch from current HEAD and check it out (`git checkout -b <name>`). Returns nil on success, error message otherwise.
func gitCreateBranch(name: String, workspacePath: String) -> String? {
    let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return "Branch name cannot be empty." }
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["checkout", "-b", trimmed]
    process.currentDirectoryURL = URL(fileURLWithPath: workspacePath)
    let errPipe = Pipe()
    process.standardError = errPipe
    guard (try? process.run()) != nil else { return "Failed to run git" }
    process.waitUntilExit()
    guard process.terminationStatus != 0 else { return nil }
    let err = (try? String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)) ?? "Unknown error"
    return err.trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Returns true if the workspace path is inside a Git repository.
func isGitRepository(workspacePath: String) -> Bool {
    let dir = URL(fileURLWithPath: workspacePath)
    guard (try? dir.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return false }

    let gitPath = dir.appendingPathComponent(".git", isDirectory: false)
    if (try? gitPath.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true {
        return true
    }

    guard FileManager.default.fileExists(atPath: gitPath.path),
          let content = try? String(contentsOf: gitPath, encoding: .utf8) else {
        return false
    }

    return content.trimmingCharacters(in: .whitespacesAndNewlines).hasPrefix("gitdir:")
}

/// Run `git init` in the workspace. Returns nil on success, error message otherwise.
func gitInit(workspacePath: String) -> String? {
    let url = URL(fileURLWithPath: workspacePath)
    guard (try? url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return "Path is not a directory." }
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["init"]
    process.currentDirectoryURL = url
    let errPipe = Pipe()
    process.standardError = errPipe
    guard (try? process.run()) != nil else { return "Failed to run git" }
    process.waitUntilExit()
    guard process.terminationStatus != 0 else { return nil }
    let err = (try? String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)) ?? "Unknown error"
    return err.trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Returns the GitHub repository web URL (https://github.com/owner/repo) if the workspace has a GitHub remote; nil otherwise.
/// Reads .git/config directly to avoid spawning a subprocess (which can SIGABRT under sandbox/main-thread).
func gitHubRepositoryURL(workspacePath: String) -> URL? {
    let dir = URL(fileURLWithPath: workspacePath)
    guard (try? dir.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return nil }
    var gitDir = dir.appendingPathComponent(".git", isDirectory: false)
    var isDir: Bool = false
    if (try? gitDir.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true {
        isDir = true
    } else if FileManager.default.fileExists(atPath: gitDir.path),
              let content = try? String(contentsOf: gitDir, encoding: .utf8),
              content.hasPrefix("gitdir:") {
        let path = content.dropFirst("gitdir:".count).trimmingCharacters(in: .whitespacesAndNewlines)
        gitDir = path.hasPrefix("/") ? URL(fileURLWithPath: path) : dir.appendingPathComponent(path)
        isDir = true
    } else {
        return nil
    }
    let configURL = isDir ? gitDir.appendingPathComponent("config", isDirectory: false) : gitDir
    guard FileManager.default.fileExists(atPath: configURL.path),
          let config = try? String(contentsOf: configURL, encoding: .utf8) else { return nil }
    let urlString = gitRemoteOriginURL(from: config)
    guard !urlString.isEmpty else { return nil }
    if urlString.hasPrefix("https://github.com/") {
        var path = String(urlString.dropFirst("https://github.com/".count))
        if path.hasSuffix(".git") { path = String(path.dropLast(4)) }
        return URL(string: "https://github.com/\(path)")
    }
    if urlString.hasPrefix("git@github.com:") {
        var path = String(urlString.dropFirst("git@github.com:".count))
        if path.hasSuffix(".git") { path = String(path.dropLast(4)) }
        return URL(string: "https://github.com/\(path)")
    }
    if urlString.hasPrefix("ssh://git@github.com/") {
        var path = String(urlString.dropFirst("ssh://git@github.com/".count))
        if path.hasSuffix(".git") { path = String(path.dropLast(4)) }
        return URL(string: "https://github.com/\(path)")
    }
    return nil
}

/// Parses git config text for `[remote "origin"]` and returns the `url = ...` value.
private func gitRemoteOriginURL(from config: String) -> String {
    let lines = config.components(separatedBy: .newlines)
    var inOrigin = false
    for line in lines {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        if trimmed.hasPrefix("[remote \"origin\"]") {
            inOrigin = true
            continue
        }
        if inOrigin {
            if trimmed.hasPrefix("[") { break }
            if trimmed.hasPrefix("url =") {
                return trimmed.dropFirst("url =".count).trimmingCharacters(in: .whitespaces)
            }
        }
    }
    return ""
}

// MARK: - Debug script helpers

enum PreferredTerminalApp: String, CaseIterable, Identifiable {
    case automatic
    case terminal
    case iTerm

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .automatic:
            return "Automatic"
        case .terminal:
            return "Terminal"
        case .iTerm:
            return "iTerm"
        }
    }

    var bundleIdentifier: String? {
        switch self {
        case .automatic:
            return nil
        case .terminal:
            return "com.apple.Terminal"
        case .iTerm:
            return "com.googlecode.iterm2"
        }
    }
}

func debugScriptURL(workspacePath: String) -> URL {
    URL(fileURLWithPath: workspacePath).appendingPathComponent("debug.sh")
}

func debugScriptExists(workspacePath: String) -> Bool {
    FileManager.default.fileExists(atPath: debugScriptURL(workspacePath: workspacePath).path)
}

func createDebugScript(workspacePath: String, contents: String) throws {
    let url = debugScriptURL(workspacePath: workspacePath)
    try contents.write(to: url, atomically: true, encoding: .utf8)
    try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
}

func launchDebugScript(workspacePath: String, preferredTerminal: PreferredTerminalApp) -> String? {
    let root = projectRootForTerminal(workspacePath: workspacePath)
    guard !root.isEmpty else {
        return "Select a workspace before running Debug."
    }

    let scriptURL = debugScriptURL(workspacePath: root)
    guard FileManager.default.fileExists(atPath: scriptURL.path) else {
        return "`debug.sh` was not found in the project root."
    }

    guard let terminal = resolvedTerminalApp(for: preferredTerminal) else {
        return "No supported terminal app is available. Install Terminal or iTerm."
    }

    let command = debugShellCommand(workspacePath: root)
    switch terminal {
    case .automatic:
        return "No supported terminal app is available. Install Terminal or iTerm."
    case .terminal:
        return runAppleScript("""
        tell application id "com.apple.Terminal"
            activate
            if (count of windows) = 0 then
                do script "\(appleScriptEscaped(command))"
            else
                do script "\(appleScriptEscaped(command))" in front window
            end if
        end tell
        """)
    case .iTerm:
        return runAppleScript("""
        tell application id "com.googlecode.iterm2"
            activate
            if (count of windows) = 0 then
                create window with default profile
            end if
            tell current window
                create tab with default profile
                tell current session of current tab
                    write text "\(appleScriptEscaped(command))"
                end tell
            end tell
        end tell
        """)
    }
}

private func resolvedTerminalApp(for preference: PreferredTerminalApp) -> PreferredTerminalApp? {
    switch preference {
    case .automatic:
        if isApplicationInstalled(bundleIdentifier: PreferredTerminalApp.iTerm.bundleIdentifier) {
            return .iTerm
        }
        if isApplicationInstalled(bundleIdentifier: PreferredTerminalApp.terminal.bundleIdentifier) {
            return .terminal
        }
        return nil
    case .terminal, .iTerm:
        guard isApplicationInstalled(bundleIdentifier: preference.bundleIdentifier) else { return nil }
        return preference
    }
}

private func isApplicationInstalled(bundleIdentifier: String?) -> Bool {
    guard let bundleIdentifier else { return false }
    return NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleIdentifier) != nil
}

private func debugShellCommand(workspacePath: String) -> String {
    let quotedPath = singleQuotedShellValue(workspacePath)
    return "cd \(quotedPath) && if [ -x ./debug.sh ]; then ./debug.sh; else bash ./debug.sh; fi"
}

private func singleQuotedShellValue(_ value: String) -> String {
    let escaped = value.replacingOccurrences(of: "'", with: "'\\''")
    return "'\(escaped)'"
}

private func appleScriptEscaped(_ value: String) -> String {
    value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
}

private func runAppleScript(_ script: String) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
    process.arguments = ["-e", script]

    let outputPipe = Pipe()
    let errorPipe = Pipe()
    process.standardOutput = outputPipe
    process.standardError = errorPipe

    do {
        try process.run()
    } catch {
        return error.localizedDescription
    }

    process.waitUntilExit()
    guard process.terminationStatus == 0 else {
        let data = errorPipe.fileHandleForReading.readDataToEndOfFile()
        let message = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return message?.isEmpty == false ? message : "Failed to launch the terminal."
    }

    return nil
}

// MARK: - Open in Browser (Chrome or directory)

private let chromeBundleId = "com.google.Chrome"

/// Opens the URL in Google Chrome if installed; otherwise opens in the default browser.
func openURLInChrome(_ url: URL) {
    guard let chromeURL = NSWorkspace.shared.urlForApplication(withBundleIdentifier: chromeBundleId) else {
        NSWorkspace.shared.open(url)
        return
    }
    NSWorkspace.shared.open([url], withApplicationAt: chromeURL, configuration: NSWorkspace.OpenConfiguration()) { _, error in
        if error != nil {
            NSWorkspace.shared.open(url)
        }
    }
}

/// Opens the workspace directory in Finder.
func openWorkspaceInFinder(workspacePath: String) {
    let url = URL(fileURLWithPath: workspacePath)
    guard FileManager.default.fileExists(atPath: url.path) else { return }
    NSWorkspace.shared.open(url)
}

// MARK: - .cursormetro → .metro migration

/// If the workspace has `.cursormetro` but not `.metro`, renames `.cursormetro` to `.metro`. Call before reading/writing project settings or tasks.
func migrateCursormetroToMetroIfNeeded(workspacePath: String) {
    let fm = FileManager.default
    let workspace = URL(fileURLWithPath: workspacePath)
    let oldDir = workspace.appendingPathComponent(".cursormetro", isDirectory: true)
    let newDir = workspace.appendingPathComponent(".metro", isDirectory: true)
    guard fm.fileExists(atPath: oldDir.path), !fm.fileExists(atPath: newDir.path) else { return }
    try? fm.moveItem(at: oldDir, to: newDir)
}

// MARK: - Startup script (run with bash in terminal)

/// Launches the project's startup script (`.metro/startup.sh`) with bash in the preferred terminal.
/// Returns an error message on failure, nil on success.
func launchStartupScript(workspacePath: String, preferredTerminal: PreferredTerminalApp) -> String? {
    let root = projectRootForTerminal(workspacePath: workspacePath)
    let scriptURL = ProjectSettingsStorage.startupScriptFileURL(workspacePath: root)
    let scriptPath = scriptURL.path
    guard FileManager.default.fileExists(atPath: scriptPath),
          let contents = ProjectSettingsStorage.getStartupScriptContents(workspacePath: root),
          !contents.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
        return "No startup script configured for this project. Add script content in Preview → Advanced (startup.sh)."
    }

    guard let terminal = resolvedTerminalApp(for: preferredTerminal) else {
        return "No supported terminal app is available. Install Terminal or iTerm."
    }

    let quotedPath = singleQuotedShellValue(root)
    let quotedScript = singleQuotedShellValue(scriptPath)
    let command = "cd \(quotedPath) && /bin/bash \(quotedScript)"

    switch terminal {
    case .automatic:
        return "No supported terminal app is available. Install Terminal or iTerm."
    case .terminal:
        return runAppleScript("""
        tell application id "com.apple.Terminal"
            activate
            if (count of windows) = 0 then
                do script "\(appleScriptEscaped(command))"
            else
                do script "\(appleScriptEscaped(command))" in front window
            end if
        end tell
        """)
    case .iTerm:
        return runAppleScript("""
        tell application id "com.googlecode.iterm2"
            activate
            if (count of windows) = 0 then
                create window with default profile
            end if
            tell current window
                create tab with default profile
                tell current session of current tab
                    write text "\(appleScriptEscaped(command))"
                end tell
            end tell
        end tell
        """)
    }
}
