import Foundation
import AppKit

// MARK: - Screenshot and prompt helpers

/// Returns the prompt with all "[Screenshot attached: path]" references removed, trimmed. Use for display only.
func userPromptDisplayText(from prompt: String) -> String {
    let pattern = "\\s*\\[Screenshot attached:\\s*[^\\]]+\\]\\s*"
    guard let regex = try? NSRegularExpression(pattern: pattern) else { return prompt }
    let range = NSRange(prompt.startIndex..., in: prompt)
    let stripped = regex.stringByReplacingMatches(
        in: prompt,
        range: range,
        withTemplate: "\n"
    )
    return stripped
        .components(separatedBy: .newlines)
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .joined(separator: "\n")
        .trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Extracts screenshot paths from prompt (e.g. ".cursor/pasted-screenshot-1.png"), capped at maxScreenshots.
func screenshotPaths(from prompt: String) -> [String] {
    let pattern = "\\[Screenshot attached:\\s*([^\\]]+)\\]"
    guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
    let range = NSRange(prompt.startIndex..., in: prompt)
    let matches = regex.matches(in: prompt, range: range)
    var paths: [String] = []
    for m in matches {
        if m.numberOfRanges > 1, let r = Range(m.range(at: 1), in: prompt) {
            let path = String(prompt[r]).trimmingCharacters(in: .whitespaces)
            if !path.isEmpty, !paths.contains(path) {
                paths.append(path)
            }
        }
    }
    return Array(paths.prefix(AppLimits.maxScreenshots))
}

func estimatedContextTokens(prompt: String, conversationCharacterCount: Int) -> (used: Int, limit: Int) {
    let chars = prompt.count + conversationCharacterCount
    let used = max(0, chars / 4)
    return (used, AppLimits.contextTokenLimit)
}

func autoGeneratedTabTitle(from prompt: String) -> String? {
    let firstContentLine = prompt
        .components(separatedBy: .newlines)
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .first { !$0.isEmpty && !$0.hasPrefix("[Screenshot attached:") }

    if let firstContentLine {
        let normalized = firstContentLine.replacingOccurrences(
            of: #"\s+"#,
            with: " ",
            options: .regularExpression
        )
        let truncated = String(normalized.prefix(72)).trimmingCharacters(in: .whitespacesAndNewlines)
        if !truncated.isEmpty { return truncated }
    }

    // Prompt is empty or only screenshot(s) — use a fallback so the tab doesn't stay "Agent N"
    if !screenshotPaths(from: prompt).isEmpty {
        return "Screenshot"
    }

    return nil
}

/// Picks the next available screenshot filename not in current paths.
func nextScreenshotPath(currentPaths: [String]) -> String? {
    let legacy = ".cursor/pasted-screenshot.png"
    if !currentPaths.contains(legacy) { return legacy }
    for i in 1...AppLimits.maxScreenshots {
        let candidate = ".cursor/pasted-screenshot-\(i).png"
        if !currentPaths.contains(candidate) { return candidate }
    }
    return nil
}

// MARK: - Project folders and Git

func loadDevFolders(rootPath: String) -> [URL] {
    let resolvedRootPath = AppPreferences.resolvedProjectsRootPath(rootPath)
    let url = URL(fileURLWithPath: resolvedRootPath)
    guard let contents = try? FileManager.default.contentsOfDirectory(
        at: url,
        includingPropertiesForKeys: [.isDirectoryKey],
        options: [.skipsHiddenFiles]
    ) else { return [] }
    return contents
        .filter { (try? $0.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true }
        .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }
}

/// Returns (current branch name, sorted list of local branch names) for the workspace. Empty if not a git repo.
func loadGitBranches(workspacePath: String) -> (current: String, branches: [String]) {
    let url = URL(fileURLWithPath: workspacePath)
    guard (try? url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return ("", []) }
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["for-each-ref", "--format=%(refname:short)", "refs/heads/"]
    process.currentDirectoryURL = url
    let pipe = Pipe()
    process.standardOutput = pipe
    process.standardError = FileHandle.nullDevice
    guard (try? process.run()) != nil else { return ("", []) }
    process.waitUntilExit()
    guard process.terminationStatus == 0 else { return ("", []) }
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    let list = (String(data: data, encoding: .utf8) ?? "")
        .split(separator: "\n")
        .map(String.init)
        .filter { !$0.isEmpty }
        .sorted { $0.localizedStandardCompare($1) == .orderedAscending }
    let currentProcess = Process()
    currentProcess.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    currentProcess.arguments = ["rev-parse", "--abbrev-ref", "HEAD"]
    currentProcess.currentDirectoryURL = url
    let currentPipe = Pipe()
    currentProcess.standardOutput = currentPipe
    currentProcess.standardError = FileHandle.nullDevice
    guard (try? currentProcess.run()) != nil else { return (list.first ?? "", list) }
    currentProcess.waitUntilExit()
    let currentData = currentPipe.fileHandleForReading.readDataToEndOfFile()
    let current = (String(data: currentData, encoding: .utf8) ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
    return (current.isEmpty ? (list.first ?? "") : current, list)
}

/// Run `git checkout <branch>` in the workspace. Returns nil on success, error message otherwise.
func gitCheckout(branch: String, workspacePath: String) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["checkout", branch]
    process.currentDirectoryURL = URL(fileURLWithPath: workspacePath)
    let pipe = Pipe()
    process.standardOutput = pipe
    let errPipe = Pipe()
    process.standardError = errPipe
    guard (try? process.run()) != nil else { return "Failed to run git" }
    process.waitUntilExit()
    guard process.terminationStatus != 0 else { return nil }
    let err = (try? String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)) ?? "Unknown error"
    return err.trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Create a new branch from current HEAD and check it out (`git checkout -b <name>`). Returns nil on success, error message otherwise.
func gitCreateBranch(name: String, workspacePath: String) -> String? {
    let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return "Branch name cannot be empty." }
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["checkout", "-b", trimmed]
    process.currentDirectoryURL = URL(fileURLWithPath: workspacePath)
    let errPipe = Pipe()
    process.standardError = errPipe
    guard (try? process.run()) != nil else { return "Failed to run git" }
    process.waitUntilExit()
    guard process.terminationStatus != 0 else { return nil }
    let err = (try? String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)) ?? "Unknown error"
    return err.trimmingCharacters(in: .whitespacesAndNewlines)
}

// MARK: - Debug script helpers

enum PreferredTerminalApp: String, CaseIterable, Identifiable {
    case automatic
    case terminal
    case iTerm

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .automatic:
            return "Automatic"
        case .terminal:
            return "Terminal"
        case .iTerm:
            return "iTerm"
        }
    }

    var bundleIdentifier: String? {
        switch self {
        case .automatic:
            return nil
        case .terminal:
            return "com.apple.Terminal"
        case .iTerm:
            return "com.googlecode.iterm2"
        }
    }
}

func debugScriptURL(workspacePath: String) -> URL {
    URL(fileURLWithPath: workspacePath).appendingPathComponent("debug.sh")
}

func debugScriptExists(workspacePath: String) -> Bool {
    FileManager.default.fileExists(atPath: debugScriptURL(workspacePath: workspacePath).path)
}

func createDebugScript(workspacePath: String, contents: String) throws {
    let url = debugScriptURL(workspacePath: workspacePath)
    try contents.write(to: url, atomically: true, encoding: .utf8)
    try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
}

func launchDebugScript(workspacePath: String, preferredTerminal: PreferredTerminalApp) -> String? {
    guard !workspacePath.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
        return "Select a workspace before running Debug."
    }

    let scriptURL = debugScriptURL(workspacePath: workspacePath)
    guard FileManager.default.fileExists(atPath: scriptURL.path) else {
        return "`debug.sh` was not found in the project root."
    }

    guard let terminal = resolvedTerminalApp(for: preferredTerminal) else {
        return "No supported terminal app is available. Install Terminal or iTerm."
    }

    let command = debugShellCommand(workspacePath: workspacePath)
    switch terminal {
    case .automatic:
        return "No supported terminal app is available. Install Terminal or iTerm."
    case .terminal:
        return runAppleScript("""
        tell application id "com.apple.Terminal"
            activate
            if (count of windows) = 0 then
                do script "\(appleScriptEscaped(command))"
            else
                do script "\(appleScriptEscaped(command))" in front window
            end if
        end tell
        """)
    case .iTerm:
        return runAppleScript("""
        tell application id "com.googlecode.iterm2"
            activate
            if (count of windows) = 0 then
                create window with default profile
            end if
            tell current window
                create tab with default profile
                tell current session of current tab
                    write text "\(appleScriptEscaped(command))"
                end tell
            end tell
        end tell
        """)
    }
}

private func resolvedTerminalApp(for preference: PreferredTerminalApp) -> PreferredTerminalApp? {
    switch preference {
    case .automatic:
        if isApplicationInstalled(bundleIdentifier: PreferredTerminalApp.iTerm.bundleIdentifier) {
            return .iTerm
        }
        if isApplicationInstalled(bundleIdentifier: PreferredTerminalApp.terminal.bundleIdentifier) {
            return .terminal
        }
        return nil
    case .terminal, .iTerm:
        guard isApplicationInstalled(bundleIdentifier: preference.bundleIdentifier) else { return nil }
        return preference
    }
}

private func isApplicationInstalled(bundleIdentifier: String?) -> Bool {
    guard let bundleIdentifier else { return false }
    return NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleIdentifier) != nil
}

private func debugShellCommand(workspacePath: String) -> String {
    let quotedPath = singleQuotedShellValue(workspacePath)
    return "cd \(quotedPath) && if [ -x ./debug.sh ]; then ./debug.sh; else bash ./debug.sh; fi"
}

private func singleQuotedShellValue(_ value: String) -> String {
    let escaped = value.replacingOccurrences(of: "'", with: "'\\''")
    return "'\(escaped)'"
}

private func appleScriptEscaped(_ value: String) -> String {
    value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
}

private func runAppleScript(_ script: String) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
    process.arguments = ["-e", script]

    let outputPipe = Pipe()
    let errorPipe = Pipe()
    process.standardOutput = outputPipe
    process.standardError = errorPipe

    do {
        try process.run()
    } catch {
        return error.localizedDescription
    }

    process.waitUntilExit()
    guard process.terminationStatus == 0 else {
        let data = errorPipe.fileHandleForReading.readDataToEndOfFile()
        let message = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return message?.isEmpty == false ? message : "Failed to launch the terminal."
    }

    return nil
}
