import Foundation
import AppKit

// MARK: - Screenshot and prompt helpers

/// Extracts screenshot paths from prompt (e.g. ".cursor/pasted-screenshot-1.png"), capped at maxScreenshots.
func screenshotPaths(from prompt: String) -> [String] {
    let pattern = "\\[Screenshot attached:\\s*([^\\]]+)\\]"
    guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
    let range = NSRange(prompt.startIndex..., in: prompt)
    let matches = regex.matches(in: prompt, range: range)
    var paths: [String] = []
    for m in matches {
        if m.numberOfRanges > 1, let r = Range(m.range(at: 1), in: prompt) {
            let path = String(prompt[r]).trimmingCharacters(in: .whitespaces)
            if !path.isEmpty, !paths.contains(path) {
                paths.append(path)
            }
        }
    }
    return Array(paths.prefix(AppLimits.maxScreenshots))
}

func estimatedContextTokens(prompt: String, conversationCharacterCount: Int) -> (used: Int, limit: Int) {
    let chars = prompt.count + conversationCharacterCount
    let used = max(0, chars / 4)
    return (used, AppLimits.contextTokenLimit)
}

func autoGeneratedTabTitle(from prompt: String) -> String? {
    let firstContentLine = prompt
        .components(separatedBy: .newlines)
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .first { !$0.isEmpty && !$0.hasPrefix("[Screenshot attached:") }

    guard let firstContentLine else { return nil }

    let normalized = firstContentLine.replacingOccurrences(
        of: #"\s+"#,
        with: " ",
        options: .regularExpression
    )

    let truncated = String(normalized.prefix(72)).trimmingCharacters(in: .whitespacesAndNewlines)
    return truncated.isEmpty ? nil : truncated
}

/// Picks the next available screenshot filename not in current paths.
func nextScreenshotPath(currentPaths: [String]) -> String? {
    let legacy = ".cursor/pasted-screenshot.png"
    if !currentPaths.contains(legacy) { return legacy }
    for i in 1...AppLimits.maxScreenshots {
        let candidate = ".cursor/pasted-screenshot-\(i).png"
        if !currentPaths.contains(candidate) { return candidate }
    }
    return nil
}

// MARK: - Project folders and Git

func loadDevFolders(rootPath: String) -> [URL] {
    let resolvedRootPath = AppPreferences.resolvedProjectsRootPath(rootPath)
    let url = URL(fileURLWithPath: resolvedRootPath)
    guard let contents = try? FileManager.default.contentsOfDirectory(
        at: url,
        includingPropertiesForKeys: [.isDirectoryKey],
        options: [.skipsHiddenFiles]
    ) else { return [] }
    return contents
        .filter { (try? $0.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true }
        .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }
}

/// Returns (current branch name, sorted list of local branch names) for the workspace. Empty if not a git repo.
func loadGitBranches(workspacePath: String) -> (current: String, branches: [String]) {
    let url = URL(fileURLWithPath: workspacePath)
    guard (try? url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return ("", []) }
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["for-each-ref", "--format=%(refname:short)", "refs/heads/"]
    process.currentDirectoryURL = url
    let pipe = Pipe()
    process.standardOutput = pipe
    process.standardError = FileHandle.nullDevice
    guard (try? process.run()) != nil else { return ("", []) }
    process.waitUntilExit()
    guard process.terminationStatus == 0 else { return ("", []) }
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    let list = (String(data: data, encoding: .utf8) ?? "")
        .split(separator: "\n")
        .map(String.init)
        .filter { !$0.isEmpty }
        .sorted { $0.localizedStandardCompare($1) == .orderedAscending }
    let currentProcess = Process()
    currentProcess.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    currentProcess.arguments = ["rev-parse", "--abbrev-ref", "HEAD"]
    currentProcess.currentDirectoryURL = url
    let currentPipe = Pipe()
    currentProcess.standardOutput = currentPipe
    currentProcess.standardError = FileHandle.nullDevice
    guard (try? currentProcess.run()) != nil else { return (list.first ?? "", list) }
    currentProcess.waitUntilExit()
    let currentData = currentPipe.fileHandleForReading.readDataToEndOfFile()
    let current = (String(data: currentData, encoding: .utf8) ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
    return (current.isEmpty ? (list.first ?? "") : current, list)
}

/// Run `git checkout <branch>` in the workspace. Returns nil on success, error message otherwise.
func gitCheckout(branch: String, workspacePath: String) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["checkout", branch]
    process.currentDirectoryURL = URL(fileURLWithPath: workspacePath)
    let pipe = Pipe()
    process.standardOutput = pipe
    let errPipe = Pipe()
    process.standardError = errPipe
    guard (try? process.run()) != nil else { return "Failed to run git" }
    process.waitUntilExit()
    guard process.terminationStatus != 0 else { return nil }
    let err = (try? String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)) ?? "Unknown error"
    return err.trimmingCharacters(in: .whitespacesAndNewlines)
}
