import Foundation
import AppKit

// MARK: - Screenshot and prompt helpers

private let attachedScreenshotRegex = try? NSRegularExpression(pattern: "\\[Screenshot attached:\\s*([^\\]]+)\\]")
private let attachedScreenshotDisplayRegex = try? NSRegularExpression(pattern: "\\s*\\[Screenshot attached:\\s*[^\\]]+\\]\\s*")

/// Returns the prompt with all "[Screenshot attached: path]" references removed, trimmed. Use for display only.
func userPromptDisplayText(from prompt: String) -> String {
    guard let regex = attachedScreenshotDisplayRegex else { return prompt }
    let range = NSRange(prompt.startIndex..., in: prompt)
    let stripped = regex.stringByReplacingMatches(
        in: prompt,
        range: range,
        withTemplate: "\n"
    )
    return stripped
        .components(separatedBy: .newlines)
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .joined(separator: "\n")
        .trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Extracts screenshot paths from prompt (e.g. ".metro/pasted-screenshot-1.png"), capped at maxScreenshots.
func screenshotPaths(from prompt: String) -> [String] {
    guard let regex = attachedScreenshotRegex else { return [] }
    let range = NSRange(prompt.startIndex..., in: prompt)
    let matches = regex.matches(in: prompt, range: range)
    var paths: [String] = []
    for m in matches {
        if m.numberOfRanges > 1, let r = Range(m.range(at: 1), in: prompt) {
            let path = String(prompt[r]).trimmingCharacters(in: .whitespaces)
            if !path.isEmpty, !paths.contains(path) {
                paths.append(path)
            }
        }
    }
    return Array(paths.prefix(AppLimits.maxScreenshots))
}

func estimatedContextTokens(prompt: String, conversationCharacterCount: Int) -> (used: Int, limit: Int) {
    let chars = prompt.count + conversationCharacterCount
    let used = max(0, chars / 4)
    return (used, AppLimits.contextTokenLimit)
}

func autoGeneratedTabTitle(from prompt: String) -> String? {
    let firstContentLine = prompt
        .components(separatedBy: .newlines)
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .first { !$0.isEmpty && !$0.hasPrefix("[Screenshot attached:") }

    if let firstContentLine {
        let normalized = firstContentLine.replacingOccurrences(
            of: #"\s+"#,
            with: " ",
            options: .regularExpression
        )
        let truncated = String(normalized.prefix(72)).trimmingCharacters(in: .whitespacesAndNewlines)
        if !truncated.isEmpty { return truncated }
    }

    // Prompt is empty or only screenshot(s) — use a fallback so the tab doesn't stay "Agent N"
    if !screenshotPaths(from: prompt).isEmpty {
        return "Screenshot"
    }

    return nil
}

/// Picks the next available screenshot filename not in current paths (legacy workspace-relative paths).
func nextScreenshotPath(currentPaths: [String]) -> String? {
    let legacy = ".metro/pasted-screenshot.png"
    if !currentPaths.contains(legacy) { return legacy }
    for i in 1...AppLimits.maxScreenshots {
        let candidate = ".metro/pasted-screenshot-\(i).png"
        if !currentPaths.contains(candidate) { return candidate }
    }
    return nil
}

// MARK: - Screenshot cache (tmp in app support, same location as preferences/tab state)

/// Directory where pasted screenshots are stored: ~/Library/Application Support/CursorPlus/tmp. Creates the directory if needed.
func screenshotCacheDirectoryURL() -> URL {
    let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
    let dir = base.appendingPathComponent("CursorPlus", isDirectory: true).appendingPathComponent("tmp", isDirectory: true)
    try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
    return dir
}

/// Returns a unique full path for a new screenshot in the cache (for use in [Screenshot attached: path]).
func nextScreenshotCachePath() -> String {
    screenshotCacheDirectoryURL()
        .appendingPathComponent("\(UUID().uuidString).png")
        .path
}

/// Resolves a screenshot path from a prompt to a file URL. Path may be absolute (cache) or workspace-relative (legacy).
/// Use this when loading or deleting; missing files are handled by callers (e.g. NSImage(contentsOf:) returns nil).
func screenshotFileURL(path: String, workspacePath: String) -> URL {
    let trimmed = path.trimmingCharacters(in: .whitespaces)
    if trimmed.hasPrefix("/") {
        return URL(fileURLWithPath: trimmed)
    }
    return URL(fileURLWithPath: workspacePath).appendingPathComponent(trimmed)
}

/// Deletes screenshot cache files older than the given number of days. Call on app quit.
func deleteScreenshotCacheOlderThan(days: Int) {
    let dir = screenshotCacheDirectoryURL()
    let cutoff = Date().addingTimeInterval(-Double(days * 24 * 60 * 60))
    guard let contents = try? FileManager.default.contentsOfDirectory(
        at: dir,
        includingPropertiesForKeys: [.contentModificationDateKey],
        options: [.skipsHiddenFiles]
    ) else { return }
    for url in contents where url.pathExtension.lowercased() == "png" {
        guard let date = (try? url.resourceValues(forKeys: [.contentModificationDateKey]))?.contentModificationDate else { continue }
        if date < cutoff {
            try? FileManager.default.removeItem(at: url)
        }
    }
}

// MARK: - Project root (terminal / process working directory)

/// Returns the project root for running terminal or process. If `workspacePath` ends with `/.metro`, returns the parent directory so the shell/agent runs in the project root, not inside `.metro`.
func projectRootForTerminal(workspacePath: String) -> String {
    let trimmed = workspacePath.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return trimmed }
    let expanded = (trimmed as NSString).expandingTildeInPath
    let url = URL(fileURLWithPath: expanded)
    if url.lastPathComponent == ".metro" {
        return url.deletingLastPathComponent().path
    }
    return expanded
}

// MARK: - Project folders and Git

/// Returns immediate subdirectories of `rootPath` that contain a `.metro` directory (Metro projects only).
func loadDevFolders(rootPath: String) -> [URL] {
    let resolvedRootPath = AppPreferences.resolvedProjectsRootPath(rootPath)
    let url = URL(fileURLWithPath: resolvedRootPath)
    guard let contents = try? FileManager.default.contentsOfDirectory(
        at: url,
        includingPropertiesForKeys: [.isDirectoryKey],
        options: [.skipsHiddenFiles]
    ) else { return [] }
    let fm = FileManager.default
    return contents
        .filter { candidate in
            guard (try? candidate.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return false }
            let metroDir = candidate.appendingPathComponent(".metro", isDirectory: true)
            var isDir: ObjCBool = false
            return fm.fileExists(atPath: metroDir.path, isDirectory: &isDir) && isDir.boolValue
        }
        .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }
}

/// Ensures every immediate subdirectory of `rootPath` has a `.metro` directory so Metro can discover it.
/// Returns the number of `.metro` directories created during this pass.
@discardableResult
func seedMetroDirectories(rootPath: String) -> Int {
    let resolvedRootPath = AppPreferences.resolvedProjectsRootPath(rootPath)
    let rootURL = URL(fileURLWithPath: resolvedRootPath)
    guard let contents = try? FileManager.default.contentsOfDirectory(
        at: rootURL,
        includingPropertiesForKeys: [.isDirectoryKey],
        options: [.skipsHiddenFiles]
    ) else { return 0 }

    let fm = FileManager.default
    var createdCount = 0
    for candidate in contents {
        guard (try? candidate.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { continue }

        let metroDir = candidate.appendingPathComponent(".metro", isDirectory: true)
        var isDir: ObjCBool = false
        if fm.fileExists(atPath: metroDir.path, isDirectory: &isDir), isDir.boolValue {
            continue
        }

        do {
            try fm.createDirectory(at: metroDir, withIntermediateDirectories: true)
            createdCount += 1
        } catch {
            continue
        }
    }

    return createdCount
}

/// Seeds `.metro` directories across multiple scan roots, deduplicated by normalized path.
/// Returns the total number of `.metro` directories created.
@discardableResult
func seedMetroDirectories(rootPaths: [String]) -> Int {
    var seen = Set<String>()
    return rootPaths.reduce(into: 0) { total, path in
        let normalized = (path as NSString).standardizingPath
        guard !normalized.isEmpty, seen.insert(normalized).inserted else { return }
        total += seedMetroDirectories(rootPath: normalized)
    }
}

/// Returns Metro projects discovered under any of the configured scan roots, deduplicated by path.
func loadDevFolders(rootPaths: [String]) -> [URL] {
    var seen = Set<String>()
    return rootPaths
        .flatMap(loadDevFolders(rootPath:))
        .filter { seen.insert($0.path).inserted }
        .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }
}

/// Returns true when the workspace contains a `.metro` directory.
func hasMetroDirectory(workspacePath: String) -> Bool {
    let metroDir = URL(fileURLWithPath: workspacePath).appendingPathComponent(".metro", isDirectory: true)
    var isDir: ObjCBool = false
    return FileManager.default.fileExists(atPath: metroDir.path, isDirectory: &isDir) && isDir.boolValue
}

/// Returns true when the workspace has `.metro/project.json`.
func hasMetroProjectSettings(workspacePath: String) -> Bool {
    let settingsURL = URL(fileURLWithPath: workspacePath)
        .appendingPathComponent(".metro", isDirectory: true)
        .appendingPathComponent("project.json", isDirectory: false)
    return FileManager.default.fileExists(atPath: settingsURL.path)
}

struct WorkspaceOperationError: LocalizedError {
    let message: String

    var errorDescription: String? { message }
}

/// Reads the default branch name from .git/HEAD (e.g. "ref: refs/heads/main" -> "main"). Returns nil if not a symbolic ref or not a git repo.
func gitDefaultBranchName(workspacePath: String) -> String? {
    let headURL = URL(fileURLWithPath: workspacePath).appendingPathComponent(".git/HEAD", isDirectory: false)
    guard let content = try? String(contentsOf: headURL, encoding: .utf8) else { return nil }
    let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
    let prefix = "ref: refs/heads/"
    guard trimmed.hasPrefix(prefix) else { return nil }
    let name = String(trimmed.dropFirst(prefix.count)).trimmingCharacters(in: .whitespacesAndNewlines)
    return name.isEmpty ? nil : name
}

/// Returns (current branch name, sorted list of local branch names) for the workspace. Empty if not a git repo.
func loadGitBranches(workspacePath: String) -> (current: String, branches: [String]) {
    let url = URL(fileURLWithPath: workspacePath)
    guard (try? url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return ("", []) }
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["for-each-ref", "--format=%(refname:short)", "refs/heads/"]
    process.currentDirectoryURL = url
    let pipe = Pipe()
    process.standardOutput = pipe
    process.standardError = FileHandle.nullDevice
    guard (try? process.run()) != nil else { return ("", []) }
    process.waitUntilExit()
    guard process.terminationStatus == 0 else { return ("", []) }
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    var list = (String(data: data, encoding: .utf8) ?? "")
        .split(separator: "\n")
        .map(String.init)
        .filter { !$0.isEmpty }
        .sorted { $0.localizedStandardCompare($1) == .orderedAscending }
    let currentProcess = Process()
    currentProcess.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    currentProcess.arguments = ["rev-parse", "--abbrev-ref", "HEAD"]
    currentProcess.currentDirectoryURL = url
    let currentPipe = Pipe()
    currentProcess.standardOutput = currentPipe
    currentProcess.standardError = FileHandle.nullDevice
    guard (try? currentProcess.run()) != nil else { return (list.first ?? "", list) }
    currentProcess.waitUntilExit()
    let currentData = currentPipe.fileHandleForReading.readDataToEndOfFile()
    var current = (String(data: currentData, encoding: .utf8) ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
    // Fresh git init: no commits yet so rev-parse returns "HEAD" but .git/HEAD points to refs/heads/main (or init.defaultBranch). Show that name.
    if current == "HEAD", list.isEmpty, let defaultBranch = gitDefaultBranchName(workspacePath: workspacePath) {
        current = defaultBranch
        list = [defaultBranch]
    }
    return (current.isEmpty ? (list.first ?? "") : current, list)
}

/// Run `git checkout <branch>` in the workspace. Returns nil on success, error message otherwise.
func gitCheckout(branch: String, workspacePath: String) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["checkout", branch]
    process.currentDirectoryURL = URL(fileURLWithPath: workspacePath)
    let pipe = Pipe()
    process.standardOutput = pipe
    let errPipe = Pipe()
    process.standardError = errPipe
    guard (try? process.run()) != nil else { return "Failed to run git" }
    process.waitUntilExit()
    guard process.terminationStatus != 0 else { return nil }
    let err = (try? String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)) ?? "Unknown error"
    return err.trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Create a new branch from current HEAD and check it out (`git checkout -b <name>`). Returns nil on success, error message otherwise.
func gitCreateBranch(name: String, workspacePath: String) -> String? {
    let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return "Branch name cannot be empty." }
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["checkout", "-b", trimmed]
    process.currentDirectoryURL = URL(fileURLWithPath: workspacePath)
    let errPipe = Pipe()
    process.standardError = errPipe
    guard (try? process.run()) != nil else { return "Failed to run git" }
    process.waitUntilExit()
    guard process.terminationStatus != 0 else { return nil }
    let err = (try? String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)) ?? "Unknown error"
    return err.trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Returns true if the workspace path is inside a Git repository.
func isGitRepository(workspacePath: String) -> Bool {
    let dir = URL(fileURLWithPath: workspacePath)
    guard (try? dir.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return false }

    let gitPath = dir.appendingPathComponent(".git", isDirectory: false)
    if (try? gitPath.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true {
        return true
    }

    guard FileManager.default.fileExists(atPath: gitPath.path),
          let content = try? String(contentsOf: gitPath, encoding: .utf8) else {
        return false
    }

    return content.trimmingCharacters(in: .whitespacesAndNewlines).hasPrefix("gitdir:")
}

/// Run `git init` in the workspace. Returns nil on success, error message otherwise.
func gitInit(workspacePath: String) -> String? {
    let url = URL(fileURLWithPath: workspacePath)
    guard (try? url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return "Path is not a directory." }
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    process.arguments = ["init"]
    process.currentDirectoryURL = url
    let errPipe = Pipe()
    process.standardError = errPipe
    guard (try? process.run()) != nil else { return "Failed to run git" }
    process.waitUntilExit()
    guard process.terminationStatus != 0 else { return nil }
    let err = (try? String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)) ?? "Unknown error"
    return err.trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Sanitizes a project/folder name for safe filesystem use: spaces become hyphens, only letters, numbers, hyphens, and underscores allowed.
func sanitizedProjectName(_ name: String) -> String {
    let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
    let withHyphens = trimmed.replacingOccurrences(of: " ", with: "-")
    let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_"))
    return withHyphens
        .unicodeScalars
        .filter { allowed.contains($0) }
        .map { Character($0) }
        .reduce(into: "") { $0.append($1) }
        .replacingOccurrences(of: "-+", with: "-", options: .regularExpression)
        .trimmingCharacters(in: CharacterSet(charactersIn: "-"))
}

/// Creates a short default folder name from a free-form idea by keeping only the first few words.
func suggestedProjectFolderName(from idea: String, maxWords: Int = 4) -> String {
    guard maxWords > 0 else { return "" }
    let words = idea
        .components(separatedBy: .whitespacesAndNewlines)
        .map { $0.trimmingCharacters(in: .punctuationCharacters) }
        .filter { !$0.isEmpty }

    return sanitizedProjectName(words.prefix(maxWords).joined(separator: " "))
}

/// Creates the given project directory inside the parent directory if it doesn't already exist.
/// Returns the created directory path on success or an error message on failure.
func createProjectDirectory(parentPath: String, folderName: String) -> Result<String, WorkspaceOperationError> {
    let resolvedParent = (parentPath as NSString).expandingTildeInPath
    let trimmedFolderName = sanitizedProjectName(folderName)
    guard !trimmedFolderName.isEmpty else {
        return .failure(WorkspaceOperationError(message: "Project name cannot be empty."))
    }

    let parentURL = URL(fileURLWithPath: resolvedParent)
    var isDir: ObjCBool = false
    guard FileManager.default.fileExists(atPath: parentURL.path, isDirectory: &isDir), isDir.boolValue else {
        return .failure(WorkspaceOperationError(message: "Choose a valid destination folder."))
    }

    let projectURL = parentURL.appendingPathComponent(trimmedFolderName, isDirectory: true)
    guard !FileManager.default.fileExists(atPath: projectURL.path) else {
        return .failure(WorkspaceOperationError(message: "A folder named \"\(trimmedFolderName)\" already exists there."))
    }

    do {
        try FileManager.default.createDirectory(at: projectURL, withIntermediateDirectories: true)
        return .success(projectURL.path)
    } catch {
        return .failure(WorkspaceOperationError(message: error.localizedDescription))
    }
}

/// Clones a Git repository into the destination folder. Returns the cloned directory path on success.
func cloneRepository(repositoryURL: String, destinationParentPath: String, folderName: String?) -> Result<String, WorkspaceOperationError> {
    let trimmedURL = repositoryURL.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmedURL.isEmpty else {
        return .failure(WorkspaceOperationError(message: "Enter a repository URL."))
    }

    let resolvedParent = (destinationParentPath as NSString).expandingTildeInPath
    let parentURL = URL(fileURLWithPath: resolvedParent)
    var isDir: ObjCBool = false
    guard FileManager.default.fileExists(atPath: parentURL.path, isDirectory: &isDir), isDir.boolValue else {
        return .failure(WorkspaceOperationError(message: "Choose a valid destination folder."))
    }

    let trimmedFolderName = folderName?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
    let destinationURL = trimmedFolderName.isEmpty
        ? nil
        : parentURL.appendingPathComponent(trimmedFolderName, isDirectory: true)
    if let destinationURL, FileManager.default.fileExists(atPath: destinationURL.path) {
        return .failure(WorkspaceOperationError(message: "A folder named \"\(trimmedFolderName)\" already exists there."))
    }

    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    var arguments = ["clone", trimmedURL]
    if let destinationURL {
        arguments.append(destinationURL.path)
    }
    process.arguments = arguments
    process.currentDirectoryURL = parentURL
    let errorPipe = Pipe()
    process.standardError = errorPipe
    process.standardOutput = Pipe()

    do {
        try process.run()
    } catch {
        return .failure(WorkspaceOperationError(message: error.localizedDescription))
    }

    process.waitUntilExit()
    guard process.terminationStatus == 0 else {
        let data = errorPipe.fileHandleForReading.readDataToEndOfFile()
        let message = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return .failure(WorkspaceOperationError(message: message?.isEmpty == false ? message! : "Git clone failed."))
    }

    if let destinationURL {
        return .success(destinationURL.path)
    }

    guard let repositoryName = inferredRepositoryFolderName(from: trimmedURL) else {
        return .failure(WorkspaceOperationError(message: "Repository cloned, but the destination folder could not be determined."))
    }
    return .success(parentURL.appendingPathComponent(repositoryName, isDirectory: true).path)
}

private func inferredRepositoryFolderName(from repositoryURL: String) -> String? {
    let trimmed = repositoryURL.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return nil }
    let lastComponent = trimmed
        .split(separator: "/")
        .last
        .map(String.init)?
        .replacingOccurrences(of: ".git", with: "")
        .trimmingCharacters(in: .whitespacesAndNewlines)
    return lastComponent?.isEmpty == false ? lastComponent : nil
}

enum RepositoryHostingProvider {
    case github
    case azureDevOps

    var menuTitle: String {
        switch self {
        case .github:
            return "GitHub"
        case .azureDevOps:
            return "Azure DevOps"
        }
    }
}

struct RepositoryHostingDestination {
    let provider: RepositoryHostingProvider
    let url: URL
}

/// Returns a supported repository hosting destination for the workspace's `origin` remote.
/// Reads .git/config directly to avoid spawning a subprocess (which can SIGABRT under sandbox/main-thread).
func repositoryHostingDestination(workspacePath: String) -> RepositoryHostingDestination? {
    let dir = URL(fileURLWithPath: workspacePath)
    guard (try? dir.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else { return nil }
    var gitDir = dir.appendingPathComponent(".git", isDirectory: false)
    var isDir: Bool = false
    if (try? gitDir.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true {
        isDir = true
    } else if FileManager.default.fileExists(atPath: gitDir.path),
              let content = try? String(contentsOf: gitDir, encoding: .utf8),
              content.hasPrefix("gitdir:") {
        let path = content.dropFirst("gitdir:".count).trimmingCharacters(in: .whitespacesAndNewlines)
        gitDir = path.hasPrefix("/") ? URL(fileURLWithPath: path) : dir.appendingPathComponent(path)
        isDir = true
    } else {
        return nil
    }
    let configURL = isDir ? gitDir.appendingPathComponent("config", isDirectory: false) : gitDir
    guard FileManager.default.fileExists(atPath: configURL.path),
          let config = try? String(contentsOf: configURL, encoding: .utf8) else { return nil }
    let urlString = gitRemoteOriginURL(from: config)
    guard !urlString.isEmpty else { return nil }
    return repositoryHostingDestination(remoteURLString: urlString)
}

/// Returns the GitHub repository web URL (https://github.com/owner/repo) if the workspace has a GitHub remote; nil otherwise.
func gitHubRepositoryURL(workspacePath: String) -> URL? {
    guard let destination = repositoryHostingDestination(workspacePath: workspacePath),
          destination.provider == .github else { return nil }
    return destination.url
}

private func repositoryHostingDestination(remoteURLString: String) -> RepositoryHostingDestination? {
    if let url = githubRepositoryURL(from: remoteURLString) {
        return RepositoryHostingDestination(provider: .github, url: url)
    }
    if let url = azureDevOpsRepositoryURL(from: remoteURLString) {
        return RepositoryHostingDestination(provider: .azureDevOps, url: url)
    }
    return nil
}

private func githubRepositoryURL(from remoteURLString: String) -> URL? {
    if remoteURLString.hasPrefix("https://github.com/") {
        var path = String(remoteURLString.dropFirst("https://github.com/".count))
        if path.hasSuffix(".git") { path = String(path.dropLast(4)) }
        return URL(string: "https://github.com/\(path)")
    }
    if remoteURLString.hasPrefix("git@github.com:") {
        var path = String(remoteURLString.dropFirst("git@github.com:".count))
        if path.hasSuffix(".git") { path = String(path.dropLast(4)) }
        return URL(string: "https://github.com/\(path)")
    }
    if remoteURLString.hasPrefix("ssh://git@github.com/") {
        var path = String(remoteURLString.dropFirst("ssh://git@github.com/".count))
        if path.hasSuffix(".git") { path = String(path.dropLast(4)) }
        return URL(string: "https://github.com/\(path)")
    }
    return nil
}

private func azureDevOpsRepositoryURL(from remoteURLString: String) -> URL? {
    let trimmed = remoteURLString.trimmingCharacters(in: .whitespacesAndNewlines)
    if trimmed.hasPrefix("https://dev.azure.com/") || trimmed.contains(".visualstudio.com/") {
        let browserURL = trimmed.hasSuffix(".git") ? String(trimmed.dropLast(4)) : trimmed
        return URL(string: browserURL)
    }
    if trimmed.hasPrefix("git@ssh.dev.azure.com:v3/") {
        var path = String(trimmed.dropFirst("git@ssh.dev.azure.com:v3/".count))
        if path.hasSuffix(".git") { path = String(path.dropLast(4)) }
        let components = path.split(separator: "/", omittingEmptySubsequences: true)
        guard components.count >= 3 else { return nil }
        return URL(string: "https://dev.azure.com/\(components[0])/\(components[1])/_git/\(components[2])")
    }
    if trimmed.hasPrefix("ssh://git@vs-ssh.visualstudio.com:22/v3/") {
        var path = String(trimmed.dropFirst("ssh://git@vs-ssh.visualstudio.com:22/v3/".count))
        if path.hasSuffix(".git") { path = String(path.dropLast(4)) }
        let components = path.split(separator: "/", omittingEmptySubsequences: true)
        guard components.count >= 3 else { return nil }
        return URL(string: "https://\(components[0]).visualstudio.com/\(components[1])/_git/\(components[2])")
    }
    return nil
}

/// Parses git config text for `[remote "origin"]` and returns the `url = ...` value.
private func gitRemoteOriginURL(from config: String) -> String {
    let lines = config.components(separatedBy: .newlines)
    var inOrigin = false
    for line in lines {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        if trimmed.hasPrefix("[remote \"origin\"]") {
            inOrigin = true
            continue
        }
        if inOrigin {
            if trimmed.hasPrefix("[") { break }
            if trimmed.hasPrefix("url =") {
                return trimmed.dropFirst("url =".count).trimmingCharacters(in: .whitespaces)
            }
        }
    }
    return ""
}

// MARK: - Debug script helpers

enum PreferredTerminalApp: String, CaseIterable, Identifiable {
    case automatic
    case terminal
    case iTerm

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .automatic:
            return "Automatic"
        case .terminal:
            return "Terminal"
        case .iTerm:
            return "iTerm"
        }
    }

    var bundleIdentifier: String? {
        switch self {
        case .automatic:
            return nil
        case .terminal:
            return "com.apple.Terminal"
        case .iTerm:
            return "com.googlecode.iterm2"
        }
    }
}

func debugScriptURL(workspacePath: String) -> URL {
    URL(fileURLWithPath: workspacePath).appendingPathComponent("debug.sh")
}

func debugScriptExists(workspacePath: String) -> Bool {
    FileManager.default.fileExists(atPath: debugScriptURL(workspacePath: workspacePath).path)
}

func createDebugScript(workspacePath: String, contents: String) throws {
    let url = debugScriptURL(workspacePath: workspacePath)
    try contents.write(to: url, atomically: true, encoding: .utf8)
    try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
}

func launchDebugScript(workspacePath: String, preferredTerminal: PreferredTerminalApp) -> String? {
    let root = projectRootForTerminal(workspacePath: workspacePath)
    guard !root.isEmpty else {
        return "Select a workspace before running Debug."
    }

    let scriptURL = debugScriptURL(workspacePath: root)
    guard FileManager.default.fileExists(atPath: scriptURL.path) else {
        return "`debug.sh` was not found in the project root."
    }

    guard let terminal = resolvedTerminalApp(for: preferredTerminal) else {
        return "No supported terminal app is available. Install Terminal or iTerm."
    }

    let command = debugShellCommand(workspacePath: root)
    switch terminal {
    case .automatic:
        return "No supported terminal app is available. Install Terminal or iTerm."
    case .terminal:
        return runAppleScript("""
        tell application id "com.apple.Terminal"
            activate
            if (count of windows) = 0 then
                do script "\(appleScriptEscaped(command))"
            else
                do script "\(appleScriptEscaped(command))" in front window
            end if
        end tell
        """)
    case .iTerm:
        return runAppleScript("""
        tell application id "com.googlecode.iterm2"
            activate
            if (count of windows) = 0 then
                create window with default profile
            end if
            tell current window
                create tab with default profile
                tell current session of current tab
                    write text "\(appleScriptEscaped(command))"
                end tell
            end tell
        end tell
        """)
    }
}

private func resolvedTerminalApp(for preference: PreferredTerminalApp) -> PreferredTerminalApp? {
    switch preference {
    case .automatic:
        if isApplicationInstalled(bundleIdentifier: PreferredTerminalApp.iTerm.bundleIdentifier) {
            return .iTerm
        }
        if isApplicationInstalled(bundleIdentifier: PreferredTerminalApp.terminal.bundleIdentifier) {
            return .terminal
        }
        return nil
    case .terminal, .iTerm:
        guard isApplicationInstalled(bundleIdentifier: preference.bundleIdentifier) else { return nil }
        return preference
    }
}

private func isApplicationInstalled(bundleIdentifier: String?) -> Bool {
    guard let bundleIdentifier else { return false }
    return NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleIdentifier) != nil
}

private func debugShellCommand(workspacePath: String) -> String {
    let quotedPath = singleQuotedShellValue(workspacePath)
    return "cd \(quotedPath) && if [ -x ./debug.sh ]; then ./debug.sh; else bash ./debug.sh; fi"
}

private func singleQuotedShellValue(_ value: String) -> String {
    let escaped = value.replacingOccurrences(of: "'", with: "'\\''")
    return "'\(escaped)'"
}

private func appleScriptEscaped(_ value: String) -> String {
    value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
}

private func runAppleScript(_ script: String) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
    process.arguments = ["-e", script]

    let outputPipe = Pipe()
    let errorPipe = Pipe()
    process.standardOutput = outputPipe
    process.standardError = errorPipe

    do {
        try process.run()
    } catch {
        return error.localizedDescription
    }

    process.waitUntilExit()
    guard process.terminationStatus == 0 else {
        let data = errorPipe.fileHandleForReading.readDataToEndOfFile()
        let message = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return message?.isEmpty == false ? message : "Failed to launch the terminal."
    }

    return nil
}

// MARK: - Open in Browser (Chrome or directory)

private let chromeBundleId = "com.google.Chrome"

/// Opens the URL in Google Chrome if installed; otherwise opens in the default browser.
func openURLInChrome(_ url: URL) {
    guard let chromeURL = NSWorkspace.shared.urlForApplication(withBundleIdentifier: chromeBundleId) else {
        NSWorkspace.shared.open(url)
        return
    }
    NSWorkspace.shared.open([url], withApplicationAt: chromeURL, configuration: NSWorkspace.OpenConfiguration()) { _, error in
        if error != nil {
            NSWorkspace.shared.open(url)
        }
    }
}

/// Opens the workspace directory in Finder.
func openWorkspaceInFinder(workspacePath: String) {
    let url = URL(fileURLWithPath: workspacePath)
    guard FileManager.default.fileExists(atPath: url.path) else { return }
    NSWorkspace.shared.open(url)
}

// MARK: - .cursormetro → .metro migration

/// If the workspace has `.cursormetro` but not `.metro`, renames `.cursormetro` to `.metro`. Call before reading/writing project settings or tasks.
func migrateCursormetroToMetroIfNeeded(workspacePath: String) {
    let fm = FileManager.default
    let workspace = URL(fileURLWithPath: workspacePath)
    let oldDir = workspace.appendingPathComponent(".cursormetro", isDirectory: true)
    let newDir = workspace.appendingPathComponent(".metro", isDirectory: true)
    guard fm.fileExists(atPath: oldDir.path), !fm.fileExists(atPath: newDir.path) else { return }
    try? fm.moveItem(at: oldDir, to: newDir)
}

// MARK: - Startup scripts (from project.json; each run in its own terminal)

/// If script is "startup.sh" or ".metro/startup.sh" and that file exists, returns its contents; otherwise returns script as-is.
/// Handles configs where the agent wrongly put a filename in the scripts array instead of actual commands.
private func resolveScriptForExecution(script: String, projectRoot: String) -> String {
    let trimmed = script.trimmingCharacters(in: .whitespacesAndNewlines)
    guard trimmed == "startup.sh" || trimmed == ".metro/startup.sh" else { return script }
    let fileURL = URL(fileURLWithPath: projectRoot)
        .appendingPathComponent(".metro")
        .appendingPathComponent("startup.sh")
    guard FileManager.default.fileExists(atPath: fileURL.path),
          let data = try? Data(contentsOf: fileURL),
          let contents = String(data: data, encoding: .utf8),
          !contents.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
        return script
    }
    return contents.trimmingCharacters(in: .whitespacesAndNewlines)
}

/// Builds a shell command that runs one script string from the project's scripts array (cwd = project root).
private func commandForScript(script: String, projectRoot: String) -> String {
    let resolved = resolveScriptForExecution(script: script, projectRoot: projectRoot)
    let quotedPath = singleQuotedShellValue(projectRoot)
    let quotedScript = singleQuotedShellValue(resolved)
    return "cd \(quotedPath) && /bin/bash -c \(quotedScript)"
}

/// Returns the shell command to run one startup script in the project (for embedded terminal). Cwd is project root.
func startupCommandForScript(script: String, workspacePath: String) -> String {
    let root = projectRootForTerminal(workspacePath: workspacePath)
    return commandForScript(script: script, projectRoot: root)
}

/// Launches each of the project's startup scripts in the preferred terminal (first in front window, rest in new tabs).
/// Returns an error message on failure, nil on success.
func launchStartupScript(workspacePath: String, preferredTerminal: PreferredTerminalApp) -> String? {
    let root = projectRootForTerminal(workspacePath: workspacePath)
    let scripts = ProjectSettingsStorage.getStartupScripts(workspacePath: root)
    guard !scripts.isEmpty else {
        return "No startup scripts configured. Add scripts in Preview → Advanced (project.json scripts array)."
    }

    guard let terminal = resolvedTerminalApp(for: preferredTerminal) else {
        return "No supported terminal app is available. Install Terminal or iTerm."
    }

    for (index, script) in scripts.enumerated() {
        let command = commandForScript(script: script, projectRoot: root)
        let useNewTab = index > 0
        switch terminal {
        case .automatic:
            return "No supported terminal app is available. Install Terminal or iTerm."
        case .terminal:
            if useNewTab {
                let err = runAppleScript("""
                    tell application id "com.apple.Terminal"
                        activate
                        tell front window to do script "\(appleScriptEscaped(command))"
                    end tell
                    """)
                if let e = err { return e }
            } else {
                let err = runAppleScript("""
                    tell application id "com.apple.Terminal"
                        activate
                        if (count of windows) = 0 then
                            do script "\(appleScriptEscaped(command))"
                        else
                            do script "\(appleScriptEscaped(command))" in front window
                        end if
                    end tell
                    """)
                if let e = err { return e }
            }
        case .iTerm:
            let err = runAppleScript("""
                tell application id "com.googlecode.iterm2"
                    activate
                    if (count of windows) = 0 then
                        create window with default profile
                    end if
                    tell current window
                        create tab with default profile
                        tell current session of current tab
                            write text "\(appleScriptEscaped(command))"
                        end tell
                    end tell
                end tell
                """)
            if let e = err { return e }
        }
    }
    return nil
}

// MARK: - Preview in external terminal windows (one per script, close all on Stop)

/// Title prefix for preview terminal windows (used to close all preview windows for this project).
func previewWindowTitlePrefix(workspacePath: String) -> String {
    let root = projectRootForTerminal(workspacePath: workspacePath)
    let name = (root as NSString).lastPathComponent
    let appName = AgentProviderID.resolvedFromStorage().metroAppMarketingName
    return "\(appName) Preview - \(name)"
}

/// Window title for one preview terminal (scriptIndex is 0-based). Uses scriptLabels when set (e.g. "backend"), otherwise " - 1", " - 2", or no suffix for a single script.
func previewWindowTitle(workspacePath: String, scriptIndex: Int) -> String {
    let root = projectRootForTerminal(workspacePath: workspacePath)
    let labels = ProjectSettingsStorage.getStartupScriptDisplayLabels(workspacePath: root)
    guard scriptIndex < labels.count else { return previewWindowTitlePrefix(workspacePath: workspacePath) }
    let suffix = labels.count > 1 ? " - \(labels[scriptIndex])" : ""
    return previewWindowTitlePrefix(workspacePath: workspacePath) + suffix
}

/// Launches each of the project's startup scripts in a **new** terminal window (one window per script). Returns nil on success.
/// Use closePreviewTerminalWindow(workspacePath:) when user taps Stop to close all preview windows for this project.
func launchStartupScriptInNewWindow(workspacePath: String, preferredTerminal: PreferredTerminalApp) -> String? {
    let root = projectRootForTerminal(workspacePath: workspacePath)
    let scripts = ProjectSettingsStorage.getStartupScripts(workspacePath: root)
    guard !scripts.isEmpty else {
        return "No startup scripts configured. Add scripts in Tasks → In Progress (Configure Setup) or Advanced."
    }

    guard let terminal = resolvedTerminalApp(for: preferredTerminal) else {
        return "No supported terminal app is available. Install Terminal or iTerm."
    }

    for (index, script) in scripts.enumerated() {
        let title = previewWindowTitle(workspacePath: workspacePath, scriptIndex: index)
        let titleEscaped = title.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
        let command = commandForScript(script: script, projectRoot: root)
        let commandWithTitle = "echo -ne \"\\033]0;\(titleEscaped)\\007\"; \(command)"

        switch terminal {
        case .automatic:
            return "No supported terminal app is available. Install Terminal or iTerm."
        case .terminal:
            if let err = runAppleScript("""
                tell application id "com.apple.Terminal"
                    activate
                    do script "\(appleScriptEscaped(commandWithTitle))"
                end tell
                """) {
                return err
            }
        case .iTerm:
            if let err = runAppleScript("""
                tell application id "com.googlecode.iterm2"
                    activate
                    create window with default profile
                    tell current session of current tab of current window
                        write text "\(appleScriptEscaped(commandWithTitle))"
                    end tell
                end tell
                """) {
                return err
            }
        }
    }
    return nil
}

/// Closes all preview terminal windows for this project (by window/session title prefix). Returns nil on success.
func closePreviewTerminalWindow(workspacePath: String) -> String? {
    let prefix = previewWindowTitlePrefix(workspacePath: workspacePath)
    let prefixEscaped = prefix.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
    _ = runAppleScript("""
        tell application id "com.apple.Terminal"
            repeat with w in (every window whose name starts with "\(prefixEscaped)")
                close w
            end repeat
        end tell
        """)
    _ = runAppleScript("""
        tell application id "com.googlecode.iterm2"
            repeat with w in (every window)
                try
                    if name of current session of current tab of w starts with "\(prefixEscaped)" then
                        close w
                    end if
                end try
            end repeat
        end tell
        """)
    return nil
}
